pipeline {
    agent any

    environment {
        IMAGE = "devsecops-app"
        TAG = "${BUILD_NUMBER}-${GIT_COMMIT}"
        TRIVY_CACHE_DIR = "/tmp/trivy-cache"
    }

    stages {

        
        stage('Build') {
            steps {
                sh '''
                    docker build -t $IMAGE:$TAG -f docker/Dockerfile .
                '''
            }
        }

        
        stage('Tests + Coverage') {
            steps {
                sh '''
                    set -e

                    python3 -m venv venv
                    . venv/bin/activate

                    python -m pip install --upgrade pip
                    python -m install -r app/requirements.txt

                    export PYTHONPATH=.
                    pytest --cov=app --cov-report=xml:coverage.xml
                
                    ls -l coverage.xml 
                '''
            }
        }

        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                        /opt/sonar-scanner/bin/sonar-scanner \
                        -Dproject.settings=sonar/sonar-project.properties
                    '''
                }
            }
        }

        
        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        
        stage('Security Scan (Trivy)') {
            steps {
                sh '''
                    mkdir -p $TRIVY_CACHE_DIR

                    trivy image \
                        --cache-dir $TRIVY_CACHE_DIR \
                        --severity CRITICAL,HIGH \
                        --format table \
                        -o trivy-report.txt \
                        $IMAGE:$TAG
                '''
            }
        }

       
        stage('Deploy Staging') {
            when {
                anyOf {
                    branch 'develop'
                    expression { return env.BRANCH_NAME?.startsWith("feature/") }
                }
            }
            steps {
                sh '''
                    echo "Deploying to STAGING..."

                    docker stop devsecops-staging || true
                    docker rm -f devsecops-staging || true

                    docker run -d \
                        --name devsecops-staging \
                        -p 5001:5000 \
                        $IMAGE:$TAG
                '''
            }
        }

        
        stage('Approval for Production') {
            when {
                branch 'main'
            }
            steps {
                input message: "Approve deployment to PRODUCTION?"
            }
        }

        // =========================
        // 🔹 DEPLOY PROD + ROLLBACK
        // =========================
        stage('Deploy Production') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    PREVIOUS=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep devsecops-app | grep -v "$TAG" | head -n 1 || true)

                    echo "Stopping current container..."
                    docker stop devsecops-app || true
                    docker rm -f devsecops-app || true

                    echo "Starting new version..."
                    docker run -d \
                        --name devsecops-app \
                        -p 5000:5000 \
                        $IMAGE:$TAG

                    echo "Waiting health check..."
                    sleep 5

                    curl -f http://localhost:5000/ || {
                        echo "DEPLOY FAILED - ROLLBACK INITIATED"

                        docker stop devsecops-app || true
                        docker rm -f devsecops-app || true

                        if [ ! -z "$PREVIOUS" ]; then
                            echo "Rolling back to previous image: $PREVIOUS"

                            docker run -d \
                                --name devsecops-app \
                                -p 5000:5000 \
                                $PREVIOUS
                        else
                            echo "No previous version found"
                        fi

                        exit 1
                    }
                '''
            }
        }
    }

    
    post {
        always {
            sh '''
                echo "Cleaning Docker resources..."
                docker system prune -f || true

                echo "Cleaning Trivy cache..."
                rm -rf /tmp/trivy-cache || true
            '''

            archiveArtifacts artifacts: 'trivy-report.txt', allowEmptyArchive: true
        }
    }
}