pipeline {
    agent any

    environment {
        IMAGE = "devsecops-app"
        TAG = "${BUILD_NUMBER}"
    }

    stages {

        // =========================
        // 🔹 BUILD (PR + STAGING + PROD)
        // =========================
        stage('Build') {
            steps {
                sh '''
                    docker build -t $IMAGE:$TAG -t $IMAGE:latest -f docker/Dockerfile .
                '''
            }
        }

        // =========================
        // 🔹 SONAR (PR + STAGING + PROD)
        // =========================
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                        /opt/sonar-scanner/bin/sonar-scanner \
                        -Dproject.settings=sonar/sonar-project.properties
                    '''
                }
            }
        }

        // =========================
        // 🔹 TRIVY (PR + STAGING + PROD)
        // =========================
        stage('Security Scan (Trivy)') {
            steps {
                sh '''
                    export TRIVY_CACHE_DIR=/tmp/trivy-cache-$BUILD_ID

                    trivy image \
                        --severity CRITICAL,HIGH \
                        --format table \
                        -o trivy-report.txt \
                        $IMAGE:$TAG
                '''
            }
        }

        // =========================
        // 🔹 DEPLOY STAGING (branch develop ou feature)
        // =========================
        stage('Deploy Staging') {
            when {
                anyOf {
                    branch 'develop'
                    expression { return env.BRANCH_NAME.startsWith("feature/") }
                }
            }
            steps {
                sh '''
                    echo "Deploying to STAGING..."

                    docker stop devsecops-staging || true
                    docker rm -f devsecops-staging || true

                    docker run -d \
                        --name devsecops-staging \
                        -p 5001:5000 \
                        $IMAGE:$TAG
                '''
            }
        }

        // =========================
        // 🔹 APPROVAL MANUAL (GATE)
        // =========================
        stage('Approval for Production') {
            when {
                branch 'main'
            }
            steps {
                input message: "Approve deployment to PRODUCTION?"
            }
        }

        // =========================
        // 🔹 DEPLOY PROD (main only)
        // =========================
        stage('Deploy Production') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    echo "Deploying to PRODUCTION..."

                    docker stop devsecops-app || true
                    docker rm -f devsecops-app || true

                    docker run -d \
                        --name devsecops-app \
                        -p 5000:5000 \
                        $IMAGE:$TAG
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'trivy-report.txt', allowEmptyArchive: true
        }
    }
}