pipeline {
    agent any

    environment {
        IMAGE = "devsecops-app"
        TAG = "${BUILD_NUMBER}-${GIT_COMMIT}"
    }

    stages {

         
        stage('Build') {
            steps {
                sh '''
                    docker build -t $IMAGE:$TAG -f docker/Dockerfile .
                '''
            }
        }

        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh '''
                        /opt/sonar-scanner/bin/sonar-scanner \
                        -Dproject.settings=sonar/sonar-project.properties
                    '''
                }
            }
        }

        
        stage('Security Scan (Trivy)') {
            steps {
                sh '''
                    export TRIVY_CACHE_DIR=/tmp/trivy-cache-$BUILD_ID

                    trivy image \
                        --severity CRITICAL,HIGH \
                        --format table \
                        -o trivy-report.txt \
                        $IMAGE:$TAG
                '''
            }
        }

        
        stage('Deploy Staging') {
            when {
                anyOf {
                    branch 'develop'
                    expression { return env.BRANCH_NAME?.startsWith("feature/") }
                }
            }
            steps {
                sh '''
                    echo "Deploying to STAGING..."

                    docker stop devsecops-staging || true
                    docker rm -f devsecops-staging || true

                    docker run -d \
                        --name devsecops-staging \
                        -p 5001:5000 \
                        $IMAGE:$TAG
                '''
            }
        }

        
        stage('Approval for Production') {
            when {
                branch 'main'
            }
            steps {
                input message: "Approve deployment to PRODUCTION?"
            }
        }

        
        stage('Deploy Production') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                    PREVIOUS=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep devsecops-app | grep -v "$TAG" | head -n 1 || true)

                    echo "Stopping current container..."
                    docker stop devsecops-app || true
                    docker rm -f devsecops-app || true

                    echo "Starting new version..."
                    docker run -d \
                        --name devsecops-app \
                        -p 5000:5000 \
                        $IMAGE:$TAG

                    echo "Waiting health check..."
                    sleep 5

                    curl -f http://localhost:5000/ || {
                        echo "DEPLOY FAILED - ROLLBACK INITIATED"

                        docker stop devsecops-app || true
                        docker rm -f devsecops-app || true

                        if [ ! -z "$PREVIOUS" ]; then
                            echo "Rolling back to previous image: $PREVIOUS"

                            docker run -d \
                                --name devsecops-app \
                                -p 5000:5000 \
                                $PREVIOUS
                        else
                            echo "No previous version found"
                        fi

                        exit 1
                    }
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'trivy-report.txt', allowEmptyArchive: true
        }
    }
}